import { AppState } from '../types';

const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();
const hoursFromNow = (hours: number) => new Date(now.getTime() + hours * 60 * 60 * 1000).toISOString();
const daysFromNow = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString();

export const initialData: AppState = {
  contacts: [
    {
      id: 'c1',
      name: 'Sarah Chen',
      company: 'Google',
      role: 'Engineering Manager',
      email: 'sarah.chen@gmail.com',
      linkedIn: 'linkedin.com/in/sarahchen',
      phone: '',
      howWeMet: 'career-fair',
      howWeMetDetail: '',
      notes: 'Very approachable. Manages a team working on Cloud infrastructure. Mentioned they\'re hiring for new grad roles in Q2.',
      status: 'hot',
      tags: ['engineering', 'google', 'new-grad'],
      createdAt: daysAgo(14),
      lastInteractionAt: daysAgo(1),
    },
    {
      id: 'c2',
      name: 'Marcus Johnson',
      company: 'Stripe',
      role: 'Senior Software Engineer',
      email: '',
      linkedIn: 'linkedin.com/in/marcusjohnson',
      phone: '',
      howWeMet: 'linkedin',
      howWeMetDetail: '',
      notes: 'Found through UChicago alumni search on LinkedIn. Works on payments infrastructure. Seems willing to chat.',
      status: 'warm',
      tags: ['engineering', 'stripe', 'alumni'],
      createdAt: daysAgo(10),
      lastInteractionAt: daysAgo(3),
    },
    {
      id: 'c3',
      name: 'Priya Patel',
      company: 'Meta',
      role: 'Technical Recruiter',
      email: 'priya.patel@meta.com',
      linkedIn: 'linkedin.com/in/priyapatel',
      phone: '555-0123',
      howWeMet: 'referral',
      howWeMetDetail: '',
      notes: 'Referred by a classmate. Handles new grad hiring for the infrastructure org. Very responsive over email.',
      status: 'active',
      tags: ['recruiter', 'meta', 'referral'],
      createdAt: daysAgo(21),
      lastInteractionAt: daysAgo(5),
    },
    {
      id: 'c4',
      name: 'James Liu',
      company: 'Figma',
      role: 'Staff Engineer',
      email: '',
      linkedIn: 'linkedin.com/in/jamesliu',
      phone: '',
      howWeMet: 'alumni-network',
      howWeMetDetail: '',
      notes: 'UChicago CS alum (class of 2018). Now leading frontend platform at Figma. Haven\'t reached out yet.',
      status: 'lead',
      tags: ['engineering', 'figma', 'alumni'],
      createdAt: daysAgo(5),
      lastInteractionAt: null,
    },
    {
      id: 'c5',
      name: 'Elena Rodriguez',
      company: 'Vortex AI',
      role: 'VP of Engineering',
      email: 'elena@vortexai.com',
      linkedIn: 'linkedin.com/in/elenarodriguez',
      phone: '',
      howWeMet: 'meetup',
      howWeMetDetail: '',
      notes: 'Met at Chicago Tech Meetup. Their startup is doing interesting work in AI infrastructure. Seemed interested in my background.',
      status: 'cold',
      tags: ['leadership', 'startup', 'ai'],
      createdAt: daysAgo(25),
      lastInteractionAt: daysAgo(25),
    },
  ],
  interactions: [
    {
      id: 'i1',
      contactId: 'c1',
      type: 'coffee-chat',
      date: daysAgo(3),
      summary: 'Coffee chat about Cloud team and new grad hiring',
      notes: 'Met at campus coffee shop. Discussed her team\'s work on Cloud Run. She suggested I apply through the internal referral system and offered to flag my application.',
      followUpNeeded: false,
    },
    {
      id: 'i2',
      contactId: 'c1',
      type: 'follow-up',
      date: daysAgo(1),
      summary: 'Sent follow-up email with resume',
      notes: 'Sent resume and a note thanking her for the referral offer. She confirmed she\'ll submit the referral this week.',
      followUpNeeded: true,
    },
    {
      id: 'i3',
      contactId: 'c2',
      type: 'outreach',
      date: daysAgo(7),
      summary: 'Sent LinkedIn connection request with note',
      notes: 'Mentioned our shared UChicago background and interest in payments infrastructure.',
      followUpNeeded: false,
    },
    {
      id: 'i4',
      contactId: 'c2',
      type: 'follow-up',
      date: daysAgo(3),
      summary: 'He accepted and replied — scheduling coffee chat',
      notes: 'He replied positively and suggested a 30-minute virtual coffee next week. Need to send available times.',
      followUpNeeded: true,
    },
    {
      id: 'i5',
      contactId: 'c3',
      type: 'outreach',
      date: daysAgo(18),
      summary: 'Initial email via referral from classmate',
      notes: 'Classmate (Ravi) introduced us over email. She responded same day with details about open roles.',
      followUpNeeded: false,
    },
    {
      id: 'i6',
      contactId: 'c3',
      type: 'interview',
      date: daysAgo(5),
      summary: 'Phone screen with Priya',
      notes: 'Standard recruiter screen. Discussed background, interest in Meta, and timeline. She said she\'d send the technical interview prep materials.',
      followUpNeeded: true,
    },
    {
      id: 'i7',
      contactId: 'c5',
      type: 'coffee-chat',
      date: daysAgo(25),
      summary: 'Met at Chicago Tech Meetup',
      notes: 'Had a great 15-minute conversation about their AI infra work. She gave me her card and said to reach out. I haven\'t followed up yet.',
      followUpNeeded: true,
    },
  ],
  actions: [
    {
      id: 'a1',
      contactId: 'c1',
      type: 'send-thankyou',
      description: 'Send thank-you note to Sarah for submitting the referral',
      dueDate: daysAgo(0),
      priority: 'high',
      completed: false,
      completedAt: null,
      createdAt: daysAgo(1),
      messageTemplate: 'Hi Sarah, thank you for taking the time to submit the referral for the Cloud team role. I especially appreciated {___}. I\'d love to stay in touch and keep you updated on my search. Best regards.',
    },
    {
      id: 'a2',
      contactId: 'c2',
      type: 'schedule-chat',
      description: 'Send Marcus available times for virtual coffee',
      dueDate: daysFromNow(1),
      priority: 'high',
      completed: false,
      completedAt: null,
      createdAt: daysAgo(3),
      messageTemplate: 'Hi Marcus, thank you for being open to connecting! I\'d love to schedule a quick chat to learn more about your work at Stripe. Would any of these times work for you? {___}',
    },
    {
      id: 'a3',
      contactId: 'c3',
      type: 'send-followup',
      description: 'Follow up with Priya about technical interview prep materials',
      dueDate: daysFromNow(2),
      priority: 'medium',
      completed: false,
      completedAt: null,
      createdAt: daysAgo(5),
      messageTemplate: 'Hi Priya, I hope you\'re doing well. I wanted to follow up on our phone screen about the technical interview prep materials you mentioned sending. I\'d love to connect and learn more about {___}. Looking forward to hearing from you.',
    },
    {
      id: 'a4',
      contactId: 'c4',
      type: 'send-outreach',
      description: 'Send initial outreach to James on LinkedIn',
      dueDate: daysFromNow(3),
      priority: 'medium',
      completed: false,
      completedAt: null,
      createdAt: daysAgo(5),
      messageTemplate: 'Hi James, I came across your profile and was impressed by your work at Figma. I\'m currently {___} and would love to learn more about your experience. Would you be open to a brief chat?',
    },
    {
      id: 'a5',
      contactId: 'c5',
      type: 'send-followup',
      description: 'Follow up with Elena — overdue since the meetup',
      dueDate: daysAgo(18),
      priority: 'low',
      completed: false,
      completedAt: null,
      createdAt: daysAgo(18),
      messageTemplate: 'Hi Elena, it\'s been a while since we connected at the Chicago Tech Meetup. I wanted to reach out because {___}. I\'d love to learn more about what Vortex AI is building.',
    },
    {
      id: 'a6',
      contactId: 'c1',
      type: 'send-followup',
      description: 'Check in with Sarah about referral status',
      dueDate: daysFromNow(5),
      priority: 'medium',
      completed: false,
      completedAt: null,
      createdAt: daysAgo(1),
      messageTemplate: null,
    },
  ],
  rules: {
    thankYouDeadlineHours: 24,
    followUpNoResponseDays: 7,
    warmContactReengageDays: 14,
    coldContactReengageDays: 30,
  },
};
